name: Greetings

on:
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet the user
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Thank you @${{ github.actor }} for raising an issue! We’re thrilled to have your input as we work together to make this project even better. Our team will review it shortly, so stay tuned! To make sure your issue gets the attention it deserves, please consider starring the repo 🌟."
          pr-message: "🎉 Thank you @${{ github.actor }} for your contribution! Your pull request has been submitted successfully, and a maintainer will review it as soon as possible. We appreciate your support in making this project better. To show your appreciation and keep us growing, please remember to star the repo 🌟!"